# action.yml
name: 'License Report'
description: 'Generate project license report'
inputs:
  format:  # id of input
    description: 'Report format Test'
    required: true
    default: 'html'
runs:
  using: 'docker'
  image: 'docker://mantisware/lic_report:latest' #'Dockerfile'